[alias]
xtask = ["run", "--release", "--package", "xtask", "--"]

emu = ["xtask", "cli", "--"]
firmware = ["xtask", "build-firmware", "--"]
dump = ["xtask", "dump-firmware", "--"]


[target.riscv64imac-unknown-none-elf]
rustflags = [
  "-C", "code-model=medium",
]