[alias]
xtask = ["run", "--release", "--package", "xtask", "--"]

cli = ["xtask", "cli", "--"]
firmware = ["xtask", "build-firmware", "--"]
dump = ["xtask", "dump-firmware", "--"]


[target.riscv64gc-unknown-none-elf]
rustflags = [
  "-C", "target-feature=-f",
  "-C", "target-feature=-d",
  "-C", "target-feature=-c",
  "-C", "code-model=medium",
]